# Replace "/home/user/" with absolute path where your InstellaVL repo resides.
datasets:
- json_path: '/home/user/InstellaVL/playground/data/instruction_tuning_data/json_files_processed/VQA-RAD.json'
- json_path: '/home/user/InstellaVL/playground/data/instruction_tuning_data/json_files_processed/infographic_vqa.json'
- json_path: '/home/user/InstellaVL/playground/data/instruction_tuning_data/json_files_processed/iconqa.json'
  sampling_strategy: random:1365
- json_path: '/home/user/InstellaVL/playground/data/instruction_tuning_data/json_files_processed/TabMWP.json'  
- json_path: '/home/user/InstellaVL/playground/data/instruction_tuning_data/json_files_processed/scienceqa_nona_context.json'  
  sampling_strategy: random:960
- json_path: '/home/user/InstellaVL/playground/data/instruction_tuning_data/json_files_processed/scienceqa_nona_context.json'  
- json_path: '/home/user/InstellaVL/playground/data/instruction_tuning_data/json_files_processed/scienceqa.json' 
  sampling_strategy: repeat:2
- json_path: '/home/user/InstellaVL/playground/data/instruction_tuning_data/json_files_processed/ureader_kg.json' 
- json_path: '/home/user/InstellaVL/playground/data/instruction_tuning_data/json_files_processed/aokvqa.json' 
- json_path: '/home/user/InstellaVL/playground/data/instruction_tuning_data/json_files_processed/k12_printing.json' 
  sampling_strategy: random:2566
- json_path: '/home/user/InstellaVL/playground/data/instruction_tuning_data/json_files_processed/tqa.json' 
  sampling_strategy: random:1365
- json_path: '/home/user/InstellaVL/playground/data/instruction_tuning_data/json_files_processed/mavis_math_metagen.json' 
- json_path: '/home/user/InstellaVL/playground/data/instruction_tuning_data/json_files_processed/magpie_pro_qwen2_72b_st.json' 
  sampling_strategy: random:150000
- json_path: '/home/user/InstellaVL/playground/data/instruction_tuning_data/json_files_processed/textocr.json' 
- json_path: '/home/user/InstellaVL/playground/data/instruction_tuning_data/json_files_processed/geo3k.json' 
- json_path: '/home/user/InstellaVL/playground/data/instruction_tuning_data/json_files_processed/TQA.json' 
  sampling_strategy: repeat:2 
- json_path: '/home/user/InstellaVL/playground/data/instruction_tuning_data/json_files_processed/magpie_pro_l3_80b_mt.json' 
  sampling_strategy: random:150000
- json_path: '/home/user/InstellaVL/playground/data/instruction_tuning_data/json_files_processed/clevr.json' 
  sampling_strategy: random:700
- json_path: '/home/user/InstellaVL/playground/data/instruction_tuning_data/json_files_processed/hitab.json'
- json_path: '/home/user/InstellaVL/playground/data/instruction_tuning_data/json_files_processed/VQA-AS.json'
- json_path: '/home/user/InstellaVL/playground/data/instruction_tuning_data/json_files_processed/robut_wtq.json'
- json_path: '/home/user/InstellaVL/playground/data/instruction_tuning_data/json_files_processed/ureader_ie.json'
- json_path: '/home/user/InstellaVL/playground/data/instruction_tuning_data/json_files_processed/hme100k.json'
  sampling_strategy: random:7450
- json_path: '/home/user/InstellaVL/playground/data/instruction_tuning_data/json_files_processed/MapQA.json'
- json_path: '/home/user/InstellaVL/playground/data/instruction_tuning_data/json_files_processed/IconQA.json'
  sampling_strategy: random:1130
- json_path: '/home/user/InstellaVL/playground/data/instruction_tuning_data/json_files_processed/diagram_image_to_text.json'
- json_path: '/home/user/InstellaVL/playground/data/instruction_tuning_data/json_files_processed/geo170k_qa.json'
- json_path: '/home/user/InstellaVL/playground/data/instruction_tuning_data/json_files_processed/rendered_text.json'
- json_path: '/home/user/InstellaVL/playground/data/instruction_tuning_data/json_files_processed/websight.json'
- json_path: '/home/user/InstellaVL/playground/data/instruction_tuning_data/json_files_processed/GEOS.json'
- json_path: '/home/user/InstellaVL/playground/data/instruction_tuning_data/json_files_processed/llavar.json'
- json_path: '/home/user/InstellaVL/playground/data/instruction_tuning_data/json_files_processed/chartqa.json'
  sampling_strategy: random:913
- json_path: '/home/user/InstellaVL/playground/data/instruction_tuning_data/json_files_processed/multihiertt.json'
- json_path: '/home/user/InstellaVL/playground/data/instruction_tuning_data/json_files_processed/cambrian_selection.json'
  sampling_strategy: repeat:2
- json_path: '/home/user/InstellaVL/playground/data/instruction_tuning_data/json_files_processed/ureader_cap.json'
- json_path: '/home/user/InstellaVL/playground/data/instruction_tuning_data/json_files_processed/lrv_normal.json'
- json_path: '/home/user/InstellaVL/playground/data/instruction_tuning_data/json_files_processed/robut_sqa.json'
- json_path: '/home/user/InstellaVL/playground/data/instruction_tuning_data/json_files_processed/CLEVR-Math.json'
- json_path: '/home/user/InstellaVL/playground/data/instruction_tuning_data/json_files_processed/chrome_writting.json'
- json_path: '/home/user/InstellaVL/playground/data/instruction_tuning_data/json_files_processed/raven.json'
  sampling_strategy: random:2100
- json_path: '/home/user/InstellaVL/playground/data/instruction_tuning_data/json_files_processed/robut_wikisql.json'
- json_path: '/home/user/InstellaVL/playground/data/instruction_tuning_data/json_files_processed/FigureQA.json'
  sampling_strategy: random:880
- json_path: '/home/user/InstellaVL/playground/data/instruction_tuning_data/json_files_processed/infographic_vqa_llava_format.json'
- json_path: '/home/user/InstellaVL/playground/data/instruction_tuning_data/json_files_processed/hateful_memes.json'
- json_path: '/home/user/InstellaVL/playground/data/instruction_tuning_data/json_files_processed/geo170k_align.json'
- json_path: '/home/user/InstellaVL/playground/data/instruction_tuning_data/json_files_processed/ureader_qa.json'
- json_path: '/home/user/InstellaVL/playground/data/instruction_tuning_data/json_files_processed/vsr.json'
- json_path: '/home/user/InstellaVL/playground/data/instruction_tuning_data/json_files_processed/dvqa.json'
  sampling_strategy: random:2000
- json_path: '/home/user/InstellaVL/playground/data/instruction_tuning_data/json_files_processed/magpie_pro_l3_80b_st.json'
  sampling_strategy: random:150000
- json_path: '/home/user/InstellaVL/playground/data/instruction_tuning_data/json_files_processed/image_textualization.json'
- json_path: '/home/user/InstellaVL/playground/data/instruction_tuning_data/json_files_processed/lrv_chart.json'
- json_path: '/home/user/InstellaVL/playground/data/instruction_tuning_data/json_files_processed/iam.json'
- json_path: '/home/user/InstellaVL/playground/data/instruction_tuning_data/json_files_processed/docvqa.json'
- json_path: '/home/user/InstellaVL/playground/data/instruction_tuning_data/json_files_processed/infographic_gpt4v.json'
- json_path: '/home/user/InstellaVL/playground/data/instruction_tuning_data/json_files_processed/vizwiz.json'
- json_path: '/home/user/InstellaVL/playground/data/instruction_tuning_data/json_files_processed/visual7w.json'
- json_path: '/home/user/InstellaVL/playground/data/instruction_tuning_data/json_files_processed/llava_next.json'
- json_path: '/home/user/InstellaVL/playground/data/instruction_tuning_data/json_files_processed/iiit5k.json'
- json_path: '/home/user/InstellaVL/playground/data/instruction_tuning_data/json_files_processed/sharegpt4v.json'
- json_path: '/home/user/InstellaVL/playground/data/instruction_tuning_data/json_files_processed/ai2d_gpt4v.json'
  sampling_strategy: repeat:2
- json_path: '/home/user/InstellaVL/playground/data/instruction_tuning_data/json_files_processed/ai2d_internvl.json'
  sampling_strategy: repeat:2
- json_path: '/home/user/InstellaVL/playground/data/instruction_tuning_data/json_files_processed/Super-CLEVR.json'
- json_path: '/home/user/InstellaVL/playground/data/instruction_tuning_data/json_files_processed/vqarad.json'
- json_path: '/home/user/InstellaVL/playground/data/instruction_tuning_data/json_files_processed/evol_instruct.json'
- json_path: '/home/user/InstellaVL/playground/data/instruction_tuning_data/json_files_processed/visualmrc.json'
- json_path: '/home/user/InstellaVL/playground/data/instruction_tuning_data/json_files_processed/ai2d_original.json'
  sampling_strategy: repeat:2
- json_path: '/home/user/InstellaVL/playground/data/instruction_tuning_data/json_files_processed/geomverse.json'
- json_path: '/home/user/InstellaVL/playground/data/instruction_tuning_data/json_files_processed/allava_instruct.json'
- json_path: '/home/user/InstellaVL/playground/data/instruction_tuning_data/json_files_processed/mathqa.json'
- json_path: '/home/user/InstellaVL/playground/data/instruction_tuning_data/json_files_processed/Geometry3K_MathV360K.json'
- json_path: '/home/user/InstellaVL/playground/data/instruction_tuning_data/json_files_processed/vision_flan.json'
- json_path: '/home/user/InstellaVL/playground/data/instruction_tuning_data/json_files_processed/GeoQA+.json'
- json_path: '/home/user/InstellaVL/playground/data/instruction_tuning_data/json_files_processed/st_vqa.json'
- json_path: '/home/user/InstellaVL/playground/data/instruction_tuning_data/json_files_processed/figureqa.json'
  sampling_strategy: random:1000
- json_path: '/home/user/InstellaVL/playground/data/instruction_tuning_data/json_files_processed/chart2text.json'
- json_path: '/home/user/InstellaVL/playground/data/instruction_tuning_data/json_files_processed/sharegpt4o.json'
- json_path: '/home/user/InstellaVL/playground/data/instruction_tuning_data/json_files_processed/PMC-VQA.json'
  sampling_strategy: random:1800
- json_path: '/home/user/InstellaVL/playground/data/instruction_tuning_data/json_files_processed/PMC-VQA.json'
- json_path: '/home/user/InstellaVL/playground/data/instruction_tuning_data/json_files_processed/screen2words.json'
- json_path: '/home/user/InstellaVL/playground/data/instruction_tuning_data/json_files_processed/mapqa.json'
- json_path: '/home/user/InstellaVL/playground/data/instruction_tuning_data/json_files_processed/intergps.json'
- json_path: '/home/user/InstellaVL/playground/data/instruction_tuning_data/json_files_processed/UniGeo.json'
- json_path: '/home/user/InstellaVL/playground/data/instruction_tuning_data/json_files_processed/textcaps.json'
- json_path: '/home/user/InstellaVL/playground/data/instruction_tuning_data/json_files_processed/vistext.json'
- json_path: '/home/user/InstellaVL/playground/data/instruction_tuning_data/json_files_processed/mavis_math_rule_geo.json'
- json_path: '/home/user/InstellaVL/playground/data/instruction_tuning_data/json_files_processed/tallyqa.json'
  sampling_strategy: random:9868
- json_path: '/home/user/InstellaVL/playground/data/instruction_tuning_data/json_files_processed/tabmwp.json'
- json_path: '/home/user/InstellaVL/playground/data/instruction_tuning_data/json_files_processed/arxivqa.json'
- json_path: '/home/user/InstellaVL/playground/data/instruction_tuning_data/json_files_processed/kvqa.json'
- json_path: '/home/user/InstellaVL/playground/data/instruction_tuning_data/json_files_processed/visual_dialog.json'
- json_path: '/home/user/InstellaVL/playground/data/instruction_tuning_data/json_files_processed/coco-goi.json'
- json_path: '/home/user/InstellaVL/playground/data/instruction_tuning_data/json_files_processed/coco-itm.json'
- json_path: '/home/user/InstellaVL/playground/data/instruction_tuning_data/json_files_processed/image-paragraph-captioning.json'
- json_path: '/home/user/InstellaVL/playground/data/instruction_tuning_data/json_files_processed/imagenet.json'
- json_path: '/home/user/InstellaVL/playground/data/instruction_tuning_data/json_files_processed/iqa.json'
- json_path: '/home/user/InstellaVL/playground/data/instruction_tuning_data/json_files_processed/localized_narratives.json'
- json_path: '/home/user/InstellaVL/playground/data/instruction_tuning_data/json_files_processed/mocheg.json'
- json_path: '/home/user/InstellaVL/playground/data/instruction_tuning_data/json_files_processed/shapes.json'
- json_path: '/home/user/InstellaVL/playground/data/instruction_tuning_data/json_files_processed/snli-ve.json'
- json_path: '/home/user/InstellaVL/playground/data/instruction_tuning_data/json_files_processed/SVIT_core_150K.json'
- json_path: '/home/user/InstellaVL/playground/data/instruction_tuning_data/json_files_processed/vcr.json'
- json_path: '/home/user/InstellaVL/playground/data/instruction_tuning_data/json_files_processed/viquae.json'
- json_path: '/home/user/InstellaVL/playground/data/instruction_tuning_data/json_files_processed/finqa.json'
- json_path: '/home/user/InstellaVL/playground/data/instruction_tuning_data/json_files_processed/web-landmark.json'
- json_path: '/home/user/InstellaVL/playground/data/instruction_tuning_data/json_files_processed/web-celebrity.json'
- json_path: '/home/user/InstellaVL/playground/data/instruction_tuning_data/json_files_processed/alfworld.json'
- json_path: '/home/user/InstellaVL/playground/data/instruction_tuning_data/json_files_processed/DocDownstream-1.0.json'
- json_path: '/home/user/InstellaVL/playground/data/instruction_tuning_data/json_files_processed/DocReason25K.json'
- json_path: '/home/user/InstellaVL/playground/data/instruction_tuning_data/json_files_processed/DocStruct4M_struct_aware_parse.json'
  sampling_strategy: random:30000
- json_path: '/home/user/InstellaVL/playground/data/instruction_tuning_data/json_files_processed/DocStruct4M_multi_grained_text_localization.json'
  sampling_strategy: random:10000
- json_path: '/home/user/InstellaVL/playground/data/instruction_tuning_data/json_files_processed/design2code.json'
- json_path: '/home/user/InstellaVL/playground/data/instruction_tuning_data/json_files_processed/hfdata.json'
- json_path: '/home/user/InstellaVL/playground/data/instruction_tuning_data/json_files_processed/lnqa.json'
- json_path: '/home/user/InstellaVL/playground/data/instruction_tuning_data/json_files_processed/TinyChartData.json'
- json_path: '/home/user/InstellaVL/playground/data/instruction_tuning_data/json_files_processed/sam.json'
- json_path: '/home/user/InstellaVL/playground/data/instruction_tuning_data/json_files_processed/Q-Instruct-DB.json'
- json_path: '/home/user/InstellaVL/playground/data/instruction_tuning_data/json_files_processed/mathvision.json'
- json_path: '/home/user/InstellaVL/playground/data/instruction_tuning_data/json_files_processed/oodvqa.json'
- json_path: '/home/user/InstellaVL/playground/data/instruction_tuning_data/json_files_processed/idk.json'
- json_path: '/home/user/InstellaVL/playground/data/instruction_tuning_data/json_files_processed/gpt4v-dataset.json'
- json_path: '/home/user/InstellaVL/playground/data/instruction_tuning_data/json_files_processed/pixmo_cap_qa_part_1.json'
- json_path: '/home/user/InstellaVL/playground/data/instruction_tuning_data/json_files_processed/pixmo_cap_qa_part_2.json'
- json_path: '/home/user/InstellaVL/playground/data/instruction_tuning_data/json_files_processed/pixmo_cap_qa_part_3.json'
- json_path: '/home/user/InstellaVL/playground/data/instruction_tuning_data/json_files_processed/pixmo_cap_qa_part_4.json'
- json_path: '/home/user/InstellaVL/playground/data/instruction_tuning_data/json_files_processed/pixmo_cap_qa_part_5.json'
- json_path: '/home/user/InstellaVL/playground/data/instruction_tuning_data/json_files_processed/pixmo_count_shards.json'
- json_path: '/home/user/InstellaVL/playground/data/instruction_tuning_data/json_files_processed/pixmo_points_part_1.json'
- json_path: '/home/user/InstellaVL/playground/data/instruction_tuning_data/json_files_processed/pixmo_point_explanations_shards.json'
- json_path: '/home/user/InstellaVL/playground/data/instruction_tuning_data/json_files_processed/pixmo_docs_tables_shards.json'
- json_path: '/home/user/InstellaVL/playground/data/instruction_tuning_data/json_files_processed/pixmo_docs_other_shards.json'
- json_path: '/home/user/InstellaVL/playground/data/instruction_tuning_data/json_files_processed/pixmo_docs_diagrams_shards.json'
- json_path: '/home/user/InstellaVL/playground/data/instruction_tuning_data/json_files_processed/pixmo_docs_charts_shards.json'
- json_path: '/home/user/InstellaVL/playground/data/instruction_tuning_data/json_files_processed/pixmo_ask_model_anything_shards.json'