# Replace "/home/user/" with absolute path where your InstellaVL repo resides.
datasets:
- json_path: '/home/user/InstellaVL/playground/data/pretraining_data/json_files_processed/LLaVA-Stage1.5.json'
- json_path: '/home/user/InstellaVL/playground/data/pretraining_data/json_files_processed/ArT.json'
- json_path: '/home/user/InstellaVL/playground/data/pretraining_data/json_files_processed/chart2text_pew.json'
- json_path: '/home/user/InstellaVL/playground/data/pretraining_data/json_files_processed/chart2text_statista.json'
- json_path: '/home/user/InstellaVL/playground/data/pretraining_data/json_files_processed/coco_text.json'
- json_path: '/home/user/InstellaVL/playground/data/pretraining_data/json_files_processed/docvqa.json'
- json_path: '/home/user/InstellaVL/playground/data/pretraining_data/json_files_processed/hiertext.json'
- json_path: '/home/user/InstellaVL/playground/data/pretraining_data/json_files_processed/mlt.json'
- json_path: '/home/user/InstellaVL/playground/data/pretraining_data/json_files_processed/mmc_instruction_arxiv.json'
- json_path: '/home/user/InstellaVL/playground/data/pretraining_data/json_files_processed/mmc_instruction_non-arxiv.json'
- json_path: '/home/user/InstellaVL/playground/data/pretraining_data/json_files_processed/M-Paper-analysis.json'
- json_path: '/home/user/InstellaVL/playground/data/pretraining_data/json_files_processed/M-Paper-cap.json'
- json_path: '/home/user/InstellaVL/playground/data/pretraining_data/json_files_processed/M-Paper-outline.json'
- json_path: '/home/user/InstellaVL/playground/data/pretraining_data/json_files_processed/openvino.json'
- json_path: '/home/user/InstellaVL/playground/data/pretraining_data/json_files_processed/Paper2Fig100k.json'
- json_path: '/home/user/InstellaVL/playground/data/pretraining_data/json_files_processed/PlotQA.json'
- json_path: '/home/user/InstellaVL/playground/data/pretraining_data/json_files_processed/Rico_ScreenQA.json'
- json_path: '/home/user/InstellaVL/playground/data/pretraining_data/json_files_processed/RICO-Screen2Words.json'
- json_path: '/home/user/InstellaVL/playground/data/pretraining_data/json_files_processed/SciGraphQA-295K-train.json'
- json_path: '/home/user/InstellaVL/playground/data/pretraining_data/json_files_processed/st_vqa.json'
- json_path: '/home/user/InstellaVL/playground/data/pretraining_data/json_files_processed/textocr.json'
- json_path: '/home/user/InstellaVL/playground/data/pretraining_data/json_files_processed/Uber-Text.json'
- json_path: '/home/user/InstellaVL/playground/data/pretraining_data/json_files_processed/UniChart.json'
  sampling_strategy: random:68983
- json_path: '/home/user/InstellaVL/playground/data/pretraining_data/json_files_processed/DocStruct4M_struct_aware_parse.json'
  sampling_strategy: random:300000
- json_path: '/home/user/InstellaVL/playground/data/pretraining_data/json_files_processed/DocStruct4M_multi_grained_text_localization.json'
  sampling_strategy: random:100000
- json_path: '/home/user/InstellaVL/playground/data/pretraining_data/json_files_processed/pixmo_cap_part_1.json'
- json_path: '/home/user/InstellaVL/playground/data/pretraining_data/json_files_processed/pixmo_cap_part_2.json'
- json_path: '/home/user/InstellaVL/playground/data/pretraining_data/json_files_processed/pixmo_cap_part_3.json'
- json_path: '/home/user/InstellaVL/playground/data/pretraining_data/json_files_processed/pixmo_cap_part_4.json'
- json_path: '/home/user/InstellaVL/playground/data/pretraining_data/json_files_processed/pixmo_cap_part_5.json'
