# Replace "/home/user/" with absolute path where your InstellaVL repo resides.
datasets:
- shard_path: '/home/user/InstellaVL/playground/data/mosaic_shards/pretraining_data/LLaVA-Stage1.5/'
- shard_path: '/home/user/InstellaVL/playground/data/mosaic_shards/pretraining_data/ArT/'
- shard_path: '/home/user/InstellaVL/playground/data/mosaic_shards/pretraining_data/chart2text_pew/'
- shard_path: '/home/user/InstellaVL/playground/data/mosaic_shards/pretraining_data/chart2text_statista/'
- shard_path: '/home/user/InstellaVL/playground/data/mosaic_shards/pretraining_data/coco_text/'
- shard_path: '/home/user/InstellaVL/playground/data/mosaic_shards/pretraining_data/docvqa/'
- shard_path: '/home/user/InstellaVL/playground/data/mosaic_shards/pretraining_data/hiertext/'
- shard_path: '/home/user/InstellaVL/playground/data/mosaic_shards/pretraining_data/mlt/'
- shard_path: '/home/user/InstellaVL/playground/data/mosaic_shards/pretraining_data/mmc_instruction_arxiv/'
- shard_path: '/home/user/InstellaVL/playground/data/mosaic_shards/pretraining_data/mmc_instruction_non-arxiv/'
- shard_path: '/home/user/InstellaVL/playground/data/mosaic_shards/pretraining_data/M-Paper-analysis/'
- shard_path: '/home/user/InstellaVL/playground/data/mosaic_shards/pretraining_data/M-Paper-cap/'
- shard_path: '/home/user/InstellaVL/playground/data/mosaic_shards/pretraining_data/M-Paper-outline/'
- shard_path: '/home/user/InstellaVL/playground/data/mosaic_shards/pretraining_data/openvino/'
- shard_path: '/home/user/InstellaVL/playground/data/mosaic_shards/pretraining_data/Paper2Fig100k/'
- shard_path: '/home/user/InstellaVL/playground/data/mosaic_shards/pretraining_data/PlotQA/'
- shard_path: '/home/user/InstellaVL/playground/data/mosaic_shards/pretraining_data/Rico_ScreenQA/'
- shard_path: '/home/user/InstellaVL/playground/data/mosaic_shards/pretraining_data/RICO-Screen2Words/'
- shard_path: '/home/user/InstellaVL/playground/data/mosaic_shards/pretraining_data/SciGraphQA-295K-train/'
- shard_path: '/home/user/InstellaVL/playground/data/mosaic_shards/pretraining_data/st_vqa/'
- shard_path: '/home/user/InstellaVL/playground/data/mosaic_shards/pretraining_data/textocr/'
- shard_path: '/home/user/InstellaVL/playground/data/mosaic_shards/pretraining_data/Uber-Text/'
- shard_path: '/home/user/InstellaVL/playground/data/mosaic_shards/pretraining_data/UniChart/'
  choose: 68983
- shard_path: '/home/user/InstellaVL/playground/data/mosaic_shards/pretraining_data/DocStruct4M_struct_aware_parse/'
  choose: 300000
- shard_path: '/home/user/InstellaVL/playground/data/mosaic_shards/pretraining_data/DocStruct4M_multi_grained_text_localization/'
  choose: 100000
- shard_path: '/home/user/InstellaVL/playground/data/mosaic_shards/pretraining_data/pixmo_cap_part_1/'
- shard_path: '/home/user/InstellaVL/playground/data/mosaic_shards/pretraining_data/pixmo_cap_part_2/'
- shard_path: '/home/user/InstellaVL/playground/data/mosaic_shards/pretraining_data/pixmo_cap_part_3/'
- shard_path: '/home/user/InstellaVL/playground/data/mosaic_shards/pretraining_data/pixmo_cap_part_4/'
- shard_path: '/home/user/InstellaVL/playground/data/mosaic_shards/pretraining_data/pixmo_cap_part_5/'
