# Replace `object_name/path/to` with the actual path starting from `object/user/...`
datasets:
- shard_path: 's3://object_name/path/to/instruction_tuning_data/VQA-RAD/'
- shard_path: 's3://object_name/path/to/instruction_tuning_data/infographic_vqa/'
- shard_path: 's3://object_name/path/to/instruction_tuning_data/iconqa/'
  choose: 1365
- shard_path: 's3://object_name/path/to/instruction_tuning_data/TabMWP/'  
- shard_path: 's3://object_name/path/to/instruction_tuning_data/scienceqa_nona_context/'  
  choose: 960
- shard_path: 's3://object_name/path/to/instruction_tuning_data/scienceqa_nona_context/'  
- shard_path: 's3://object_name/path/to/instruction_tuning_data/scienceqa/' 
  repeat: 2
- shard_path: 's3://object_name/path/to/instruction_tuning_data/ureader_kg/' 
- shard_path: 's3://object_name/path/to/instruction_tuning_data/aokvqa/' 
- shard_path: 's3://object_name/path/to/instruction_tuning_data/k12_printing/' 
  choose: 2566
- shard_path: 's3://object_name/path/to/instruction_tuning_data/tqa/' 
  choose: 1365
- shard_path: 's3://object_name/path/to/instruction_tuning_data/mavis_math_metagen/' 
- shard_path: 's3://object_name/path/to/instruction_tuning_data/magpie_pro_qwen2_72b_st/' 
  choose: 150000
- shard_path: 's3://object_name/path/to/instruction_tuning_data/textocr/' 
- shard_path: 's3://object_name/path/to/instruction_tuning_data/geo3k/' 
- shard_path: 's3://object_name/path/to/instruction_tuning_data/TQA/' 
  repeat: 2 
- shard_path: 's3://object_name/path/to/instruction_tuning_data/magpie_pro_l3_80b_mt/' 
  choose: 150000
- shard_path: 's3://object_name/path/to/instruction_tuning_data/clevr/' 
  choose: 700
- shard_path: 's3://object_name/path/to/instruction_tuning_data/hitab/'
- shard_path: 's3://object_name/path/to/instruction_tuning_data/VQA-AS/'
- shard_path: 's3://object_name/path/to/instruction_tuning_data/robut_wtq/'
- shard_path: 's3://object_name/path/to/instruction_tuning_data/ureader_ie/'
- shard_path: 's3://object_name/path/to/instruction_tuning_data/hme100k/'
  choose: 7450
- shard_path: 's3://object_name/path/to/instruction_tuning_data/MapQA/'
- shard_path: 's3://object_name/path/to/instruction_tuning_data/IconQA/'
  choose: 1130
- shard_path: 's3://object_name/path/to/instruction_tuning_data/diagram_image_to_text/'
- shard_path: 's3://object_name/path/to/instruction_tuning_data/geo170k_qa/'
- shard_path: 's3://object_name/path/to/instruction_tuning_data/rendered_text/'
- shard_path: 's3://object_name/path/to/instruction_tuning_data/websight/'
- shard_path: 's3://object_name/path/to/instruction_tuning_data/GEOS/'
- shard_path: 's3://object_name/path/to/instruction_tuning_data/llavar/'
- shard_path: 's3://object_name/path/to/instruction_tuning_data/chartqa/'
  choose: 913
- shard_path: 's3://object_name/path/to/instruction_tuning_data/multihiertt/'
- shard_path: 's3://object_name/path/to/instruction_tuning_data/cambrian_selection/'
  repeat: 2
- shard_path: 's3://object_name/path/to/instruction_tuning_data/ureader_cap/'
- shard_path: 's3://object_name/path/to/instruction_tuning_data/lrv_normal/'
- shard_path: 's3://object_name/path/to/instruction_tuning_data/robut_sqa/'
- shard_path: 's3://object_name/path/to/instruction_tuning_data/CLEVR-Math/'
- shard_path: 's3://object_name/path/to/instruction_tuning_data/chrome_writting/'
- shard_path: 's3://object_name/path/to/instruction_tuning_data/raven/'
  choose: 2100
- shard_path: 's3://object_name/path/to/instruction_tuning_data/robut_wikisql/'
- shard_path: 's3://object_name/path/to/instruction_tuning_data/FigureQA/'
  choose: 880
- shard_path: 's3://object_name/path/to/instruction_tuning_data/infographic_vqa_llava_format/'
- shard_path: 's3://object_name/path/to/instruction_tuning_data/hateful_memes/'
- shard_path: 's3://object_name/path/to/instruction_tuning_data/geo170k_align/'
- shard_path: 's3://object_name/path/to/instruction_tuning_data/ureader_qa/'
- shard_path: 's3://object_name/path/to/instruction_tuning_data/vsr/'
- shard_path: 's3://object_name/path/to/instruction_tuning_data/dvqa/'
  choose: 2000
- shard_path: 's3://object_name/path/to/instruction_tuning_data/magpie_pro_l3_80b_st/'
  choose: 150000
- shard_path: 's3://object_name/path/to/instruction_tuning_data/image_textualization/'
- shard_path: 's3://object_name/path/to/instruction_tuning_data/lrv_chart/'
- shard_path: 's3://object_name/path/to/instruction_tuning_data/iam/'
- shard_path: 's3://object_name/path/to/instruction_tuning_data/docvqa/'
- shard_path: 's3://object_name/path/to/instruction_tuning_data/infographic_gpt4v/'
- shard_path: 's3://object_name/path/to/instruction_tuning_data/vizwiz/'
- shard_path: 's3://object_name/path/to/instruction_tuning_data/visual7w/'
- shard_path: 's3://object_name/path/to/instruction_tuning_data/llava_next/'
- shard_path: 's3://object_name/path/to/instruction_tuning_data/iiit5k/'
- shard_path: 's3://object_name/path/to/instruction_tuning_data/sharegpt4v/'
- shard_path: 's3://object_name/path/to/instruction_tuning_data/ai2d_gpt4v/'
  repeat: 2
- shard_path: 's3://object_name/path/to/instruction_tuning_data/ai2d_internvl/'
  repeat: 2
- shard_path: 's3://object_name/path/to/instruction_tuning_data/Super-CLEVR/'
- shard_path: 's3://object_name/path/to/instruction_tuning_data/vqarad/'
- shard_path: 's3://object_name/path/to/instruction_tuning_data/evol_instruct/'
- shard_path: 's3://object_name/path/to/instruction_tuning_data/visualmrc/'
- shard_path: 's3://object_name/path/to/instruction_tuning_data/ai2d_original/'
  repeat: 2
- shard_path: 's3://object_name/path/to/instruction_tuning_data/geomverse/'
- shard_path: 's3://object_name/path/to/instruction_tuning_data/allava_instruct/'
- shard_path: 's3://object_name/path/to/instruction_tuning_data/mathqa/'
- shard_path: 's3://object_name/path/to/instruction_tuning_data/Geometry3K_MathV360K/'
- shard_path: 's3://object_name/path/to/instruction_tuning_data/vision_flan/'
- shard_path: 's3://object_name/path/to/instruction_tuning_data/GeoQA+/'
- shard_path: 's3://object_name/path/to/instruction_tuning_data/st_vqa/'
- shard_path: 's3://object_name/path/to/instruction_tuning_data/figureqa/'
  choose: 1000
- shard_path: 's3://object_name/path/to/instruction_tuning_data/chart2text/'
- shard_path: 's3://object_name/path/to/instruction_tuning_data/sharegpt4o/'
- shard_path: 's3://object_name/path/to/instruction_tuning_data/PMC-VQA/'
  choose: 1800
- shard_path: 's3://object_name/path/to/instruction_tuning_data/PMC-VQA/'
- shard_path: 's3://object_name/path/to/instruction_tuning_data/screen2words/'
- shard_path: 's3://object_name/path/to/instruction_tuning_data/mapqa/'
- shard_path: 's3://object_name/path/to/instruction_tuning_data/intergps/'
- shard_path: 's3://object_name/path/to/instruction_tuning_data/UniGeo/'
- shard_path: 's3://object_name/path/to/instruction_tuning_data/textcaps/'
- shard_path: 's3://object_name/path/to/instruction_tuning_data/vistext/'
- shard_path: 's3://object_name/path/to/instruction_tuning_data/mavis_math_rule_geo/'
- shard_path: 's3://object_name/path/to/instruction_tuning_data/tallyqa/'
  choose: 9868
- shard_path: 's3://object_name/path/to/instruction_tuning_data/tabmwp/'
- shard_path: 's3://object_name/path/to/instruction_tuning_data/arxivqa/'
- shard_path: 's3://object_name/path/to/instruction_tuning_data/kvqa/'
- shard_path: 's3://object_name/path/to/instruction_tuning_data/visual_dialog/'
- shard_path: 's3://object_name/path/to/instruction_tuning_data/coco-goi/'
- shard_path: 's3://object_name/path/to/instruction_tuning_data/coco-itm/'
- shard_path: 's3://object_name/path/to/instruction_tuning_data/image-paragraph-captioning/'
- shard_path: 's3://object_name/path/to/instruction_tuning_data/imagenet/'
- shard_path: 's3://object_name/path/to/instruction_tuning_data/iqa/'
- shard_path: 's3://object_name/path/to/instruction_tuning_data/localized_narratives/'
- shard_path: 's3://object_name/path/to/instruction_tuning_data/mocheg/'
- shard_path: 's3://object_name/path/to/instruction_tuning_data/shapes/'
- shard_path: 's3://object_name/path/to/instruction_tuning_data/snli-ve/'
- shard_path: 's3://object_name/path/to/instruction_tuning_data/SVIT_core_150K/'
- shard_path: 's3://object_name/path/to/instruction_tuning_data/vcr/'
- shard_path: 's3://object_name/path/to/instruction_tuning_data/viquae/'
- shard_path: 's3://object_name/path/to/instruction_tuning_data/finqa/'
- shard_path: 's3://object_name/path/to/instruction_tuning_data/web-landmark/'
- shard_path: 's3://object_name/path/to/instruction_tuning_data/web-celebrity/'
- shard_path: 's3://object_name/path/to/instruction_tuning_data/alfworld/'
- shard_path: 's3://object_name/path/to/instruction_tuning_data/DocDownstream-1.0/'
- shard_path: 's3://object_name/path/to/instruction_tuning_data/DocReason25K/'
- shard_path: 's3://object_name/path/to/instruction_tuning_data/DocStruct4M_struct_aware_parse/'
  choose: 30000
- shard_path: 's3://object_name/path/to/instruction_tuning_data/DocStruct4M_multi_grained_text_localization/'
  choose: 10000
- shard_path: 's3://object_name/path/to/instruction_tuning_data/design2code/'
- shard_path: 's3://object_name/path/to/instruction_tuning_data/hfdata/'
- shard_path: 's3://object_name/path/to/instruction_tuning_data/lnqa/'
- shard_path: 's3://object_name/path/to/instruction_tuning_data/TinyChartData/'
- shard_path: 's3://object_name/path/to/instruction_tuning_data/sam/'
- shard_path: 's3://object_name/path/to/instruction_tuning_data/Q-Instruct-DB/'
- shard_path: 's3://object_name/path/to/instruction_tuning_data/mathvision/'
- shard_path: 's3://object_name/path/to/instruction_tuning_data/oodvqa/'
- shard_path: 's3://object_name/path/to/instruction_tuning_data/idk/'
- shard_path: 's3://object_name/path/to/instruction_tuning_data/gpt4v-dataset/'
- shard_path: 's3://object_name/path/to/instruction_tuning_data/pixmo_cap_qa_part_1/'
- shard_path: 's3://object_name/path/to/instruction_tuning_data/pixmo_cap_qa_part_2/'
- shard_path: 's3://object_name/path/to/instruction_tuning_data/pixmo_cap_qa_part_3/'
- shard_path: 's3://object_name/path/to/instruction_tuning_data/pixmo_cap_qa_part_4/'
- shard_path: 's3://object_name/path/to/instruction_tuning_data/pixmo_cap_qa_part_5/'
- shard_path: 's3://object_name/path/to/instruction_tuning_data/pixmo_count_shards/'
- shard_path: 's3://object_name/path/to/instruction_tuning_data/pixmo_points_part_1/'
- shard_path: 's3://object_name/path/to/instruction_tuning_data/pixmo_point_explanations_shards/'
- shard_path: 's3://object_name/path/to/instruction_tuning_data/pixmo_docs_tables_shards/'
- shard_path: 's3://object_name/path/to/instruction_tuning_data/pixmo_docs_other_shards/'
- shard_path: 's3://object_name/path/to/instruction_tuning_data/pixmo_docs_diagrams_shards/'
- shard_path: 's3://object_name/path/to/instruction_tuning_data/pixmo_docs_charts_shards/'
- shard_path: 's3://object_name/path/to/instruction_tuning_data/pixmo_ask_model_anything_shards/'
